---
version: '2.1'

services:
  dev1.group_1:
    hostname: dev1.group_1
    image: dbarroso/stupid_ssh_container
    ports:
      - "65020:22"
    networks:
      net1:
        ipv4_address: 10.22.33.101

networks:
  net1:
    driver: bridge
    ipam:
      config:
        - subnet: 10.22.33.0/24
